package seed

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strings"
)

type Compiler struct {
	URL    string
	Key    string
	Model  string
}

func NewCompiler() *Compiler {
	c := &Compiler{
		URL:   envOr("KS_LLM_URL", "http://127.0.0.1:8080"),
		Key:   os.Getenv("KS_LLM_API_KEY"),
		Model: envOr("KS_LLM_MODEL", "local"),
	}
	return c
}

func (c *Compiler) Available() bool {
	return c.Key != ""
}

type CompiledTrio struct {
	CommandScript   string
	ProjectorScript string
}

func (c *Compiler) Compile(trio Trio) (CompiledTrio, error) {
	if !c.Available() {
		return c.stub(trio), nil
	}

	prompt := buildPrompt(trio)

	req := map[string]any{
		"model": c.Model,
		"messages": []map[string]string{
			{"role": "system", "content": systemPrompt},
			{"role": "user", "content": prompt},
		},
		"temperature": 0.2,
	}
	body, _ := json.Marshal(req)

	url := strings.TrimRight(c.URL, "/") + "/v1/chat/completions"
	r, err := http.NewRequest("POST", url, bytes.NewReader(body))
	if err != nil {
		return CompiledTrio{}, err
	}
	r.Header.Set("Content-Type", "application/json")
	r.Header.Set("Authorization", "Bearer "+c.Key)

	resp, err := http.DefaultClient.Do(r)
	if err != nil {
		return CompiledTrio{}, fmt.Errorf("llm call failed: %w (set KS_LLM_API_KEY or check KS_LLM_URL)", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != 200 {
		b, _ := io.ReadAll(resp.Body)
		return CompiledTrio{}, fmt.Errorf("llm returned %d: %s", resp.StatusCode, string(b))
	}

	var result struct {
		Choices []struct {
			Message struct {
				Content string `json:"content"`
			} `json:"message"`
		} `json:"choices"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return CompiledTrio{}, err
	}
	if len(result.Choices) == 0 {
		return CompiledTrio{}, fmt.Errorf("llm returned no choices")
	}

	return parseScripts(result.Choices[0].Message.Content, trio)
}

func (c *Compiler) stub(trio Trio) CompiledTrio {
	cmd := fmt.Sprintf("#!/usr/bin/env python3\n# STUB (no KS_LLM_API_KEY set) — generated by ks\n# Command: %s\n# Declaration: %s\nimport sys, json, time, uuid\n\nevent = {\n    \"name\": %q,\n    \"payload\": {\"title\": \" \".join(sys.argv[1:]) or \"(untitled)\"},\n}\nprint(json.dumps(event))\n",
		trio.Name, trio.Command.Description, trio.Event.Name)

	proj := fmt.Sprintf("#!/usr/bin/env python3\n# STUB (no KS_LLM_API_KEY set) — generated by ks\n# Projector: %s\n# Consumes: %s\nimport sys, json\n\nevents = []\nfor line in sys.stdin:\n    line = line.strip()\n    if not line:\n        continue\n    events.append(json.loads(line))\n\nprint(\"<html><body>\")\nprint(\"<h1>%s</h1>\")\nprint(\"<ul>\")\nfor e in events:\n    if e.get(\"name\") in %s:\n        title = e.get(\"payload\", {}).get(\"title\", \"(untitled)\")\n        print(f\"<li>{title}</li>\")\nprint(\"</ul>\")\nprint(\"</body></html>\")\n",
		trio.Projector.Name, strings.Join(trio.Projector.Consumes, ", "), trio.Projector.Name, jsonRepr(trio.Projector.Consumes))

	return CompiledTrio{CommandScript: cmd, ProjectorScript: proj}
}

func WriteScripts(dir string, trioName string, ct CompiledTrio) error {
	cmdPath := filepath.Join(dir, "commands", trioName)
	projPath := filepath.Join(dir, "projectors", trioName)

	if err := os.MkdirAll(filepath.Dir(cmdPath), 0755); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(projPath), 0755); err != nil {
		return err
	}

	if err := os.WriteFile(cmdPath, []byte(ct.CommandScript), 0755); err != nil {
		return err
	}
	if err := os.WriteFile(projPath, []byte(ct.ProjectorScript), 0755); err != nil {
		return err
	}
	return nil
}

const systemPrompt = `You are the ks compiler. You read seed declarations and write executable scripts that implement them.

The kernel runs scripts as Unix pipeline processes:
- Command script: receives command args as argv. Reads current events as JSONL on stdin. Writes new events as JSONL on stdout (one JSON object per line, fields: name, payload). The kernel assigns id, seq, occurred_at.
- Projector script: reads all events as JSONL on stdin. Writes HTML on stdout.

Write scripts in Python 3 (portable, no external deps). Include the #!/usr/bin/env python3 shebang. Keep them minimal and correct.

Return ONLY a JSON object with this shape:
{"command_script": "<full script source>", "projector_script": "<full script source>"}

No prose, no markdown fences, just the JSON object.`

func buildPrompt(trio Trio) string {
	return fmt.Sprintf(`Compile this trio into two scripts.

TRIO: %s

COMMAND declaration:
  description: %s
  params: %s

EVENT declaration:
  name: %s
  fields: %s

PROJECTOR declaration:
  name: %s
  description: %s
  consumes: %s

Write the command_script and projector_script. The command must produce an event with the declared name and populate its fields from argv params. The projector must filter events by the consumed names and render HTML.`,
		trio.Name,
		trio.Command.Description, jsonRepr(trio.Command.Params),
		trio.Event.Name, jsonRepr(trio.Event.Fields),
		trio.Projector.Name, trio.Projector.Description, jsonRepr(trio.Projector.Consumes),
	)
}

func parseScripts(content string, trio Trio) (CompiledTrio, error) {
	content = strings.TrimSpace(content)
	content = strings.TrimPrefix(content, "```json")
	content = strings.TrimPrefix(content, "```")
	content = strings.TrimSuffix(content, "```")
	content = strings.TrimSpace(content)

	var parsed struct {
		CommandScript   string `json:"command_script"`
		ProjectorScript string `json:"projector_script"`
	}
	if err := json.Unmarshal([]byte(content), &parsed); err != nil {
		return CompiledTrio{}, fmt.Errorf("parse llm output: %w\nraw: %s", err, content)
	}
	if parsed.CommandScript == "" || parsed.ProjectorScript == "" {
		return CompiledTrio{}, fmt.Errorf("llm returned empty scripts")
	}
	return CompiledTrio{CommandScript: parsed.CommandScript, ProjectorScript: parsed.ProjectorScript}, nil
}

func envOr(key, def string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return def
}

func jsonRepr(v any) string {
	b, _ := json.Marshal(v)
	return string(b)
}
