package seed

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strings"
)

type Compiler struct {
	URL   string
	Key   string
	Model string
	Stub  bool
}

func NewCompiler() *Compiler {
	if os.Getenv("KS_LLM_STUB") == "1" {
		return &Compiler{Stub: true}
	}
	url, key, model := defaultLLMConfig()
	return &Compiler{
		URL:   envOr("KS_LLM_URL", url),
		Key:   envOr("KS_LLM_API_KEY", key),
		Model: envOr("KS_LLM_MODEL", model),
	}
}

func (c *Compiler) Available() bool {
	if c.Stub {
		return false
	}
	return c.Key != ""
}

type llmConfig struct {
	URL, Key, Model string
}

func defaultLLMConfig() (url, key, model string) {
	url = "http://127.0.0.1:8080"
	model = "local"
	if cfg, ok := loadOpencodeGoConfig(opencodeAuthPath()); ok {
		url, key, model = cfg.URL, cfg.Key, cfg.Model
	}
	return
}

func loadOpencodeGoConfig(authPath string) (llmConfig, bool) {
	data, err := os.ReadFile(authPath)
	if err != nil {
		return llmConfig{}, false
	}
	var auth map[string]struct {
		Type string `json:"type"`
		Key  string `json:"key"`
	}
	if err := json.Unmarshal(data, &auth); err != nil {
		return llmConfig{}, false
	}
	entry, ok := auth["opencode-go"]
	if !ok || entry.Key == "" {
		return llmConfig{}, false
	}
	return llmConfig{
		URL:   "https://opencode.ai/zen/go",
		Key:   entry.Key,
		Model: "glm-5.2",
	}, true
}

func opencodeAuthPath() string {
	if v := os.Getenv("XDG_DATA_HOME"); v != "" {
		return filepath.Join(v, "opencode", "auth.json")
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return filepath.Join(os.Getenv("HOME"), ".local", "share", "opencode", "auth.json")
	}
	return filepath.Join(home, ".local", "share", "opencode", "auth.json")
}

func (c *Compiler) callLLM(system, user string) (string, error) {
	req := map[string]any{
		"model": c.Model,
		"messages": []map[string]string{
			{"role": "system", "content": system},
			{"role": "user", "content": user},
		},
		"temperature": 0.2,
	}
	body, _ := json.Marshal(req)

	url := strings.TrimRight(c.URL, "/") + "/v1/chat/completions"
	r, err := http.NewRequest("POST", url, bytes.NewReader(body))
	if err != nil {
		return "", err
	}
	r.Header.Set("Content-Type", "application/json")
	r.Header.Set("Authorization", "Bearer "+c.Key)

	resp, err := http.DefaultClient.Do(r)
	if err != nil {
		return "", fmt.Errorf("llm call failed: %w (set KS_LLM_API_KEY or check KS_LLM_URL)", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != 200 {
		b, _ := io.ReadAll(resp.Body)
		return "", fmt.Errorf("llm returned %d: %s", resp.StatusCode, string(b))
	}

	var result struct {
		Choices []struct {
			Message struct {
				Content string `json:"content"`
			} `json:"message"`
		} `json:"choices"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return "", err
	}
	if len(result.Choices) == 0 {
		return "", fmt.Errorf("llm returned no choices")
	}
	return result.Choices[0].Message.Content, nil
}

func (c *Compiler) CompileCommand(cmd Command) (string, error) {
	if !c.Available() {
		return c.stubCommand(cmd), nil
	}
	content, err := c.callLLM(CommandSystemPrompt, buildCommandPrompt(cmd))
	if err != nil {
		return "", err
	}
	return parseCommandScript(content)
}

func (c *Compiler) CompileProjector(p ProjectorDecl) (string, error) {
	if !c.Available() {
		return c.stubProjector(p), nil
	}
	content, err := c.callLLM(ProjectorSystemPrompt, buildProjectorPrompt(p))
	if err != nil {
		return "", err
	}
	return parseProjectorScript(content)
}

func (c *Compiler) stubCommand(cmd Command) string {
	return fmt.Sprintf("#!/usr/bin/env python3\n# STUB (no LLM configured) — generated by ks\n# Command: %s\nimport sys, json\n\nevent = {\n    \"name\": %q,\n    \"payload\": {\"title\": \" \".join(sys.argv[1:]) or \"(untitled)\"},\n}\nprint(json.dumps(event))\n",
		cmd.Description, cmd.Event.Name)
}

func (c *Compiler) stubProjector(p ProjectorDecl) string {
	return fmt.Sprintf("#!/usr/bin/env python3\n# STUB (no LLM configured) — generated by ks\n# Projector: %s\nimport sys, json\nfrom html import escape\n\nevents = []\nfor line in sys.stdin:\n    line = line.strip()\n    if not line:\n        continue\n    events.append(json.loads(line))\n\nprint(\"<!DOCTYPE html>\")\nprint(\"<html><head><title>%s</title></head><body>\")\nprint(\"<h1>%s</h1>\")\nprint(\"<ul>\")\nfor e in events:\n    if e.get(\"name\") in %s:\n        title = e.get(\"payload\", {}).get(\"title\", \"(untitled)\")\n        print(f\"  <li>{escape(title)}</li>\")\nprint(\"</ul>\")\nprint(\"</body></html>\")\n",
		p.Name, p.Name, p.Name, jsonRepr(p.Consumes))
}

func WriteCommandScript(dir string, name string, script string) error {
	cmdPath := filepath.Join(dir, "commands", name)
	if err := os.MkdirAll(filepath.Dir(cmdPath), 0755); err != nil {
		return err
	}
	return os.WriteFile(cmdPath, []byte(script), 0755)
}

func WriteProjectorScript(dir string, name string, script string) error {
	projPath := filepath.Join(dir, "projectors", name)
	if err := os.MkdirAll(filepath.Dir(projPath), 0755); err != nil {
		return err
	}
	return os.WriteFile(projPath, []byte(script), 0755)
}

const CommandSystemPrompt = `You are the ks compiler. You read a command declaration (command + the event it produces) and write an executable command script.

The kernel runs command scripts as Unix pipeline processes:
- Receives args as argv. Reads current events as JSONL on stdin. Writes new events as JSONL on stdout (one JSON object per line, fields: name, payload). The kernel assigns id, seq, occurred_at.

The kernel sets the KS_HOME env var to the kernel home directory. Commands may write persistent structured state to $KS_HOME/artefacts/<name>.json for subsequent calls to read. This is optional — most commands just emit events.

Write scripts in any language available on the system. Python 3 and bash are safe portable choices. Include the appropriate shebang. Use only standard libraries / builtins — no external dependencies.

Return ONLY a JSON object with this shape:
{"command_script": "<full script source>"}

No prose, no markdown fences, just the JSON object.`

const ProjectorSystemPrompt = `You are the ks compiler. You read a projector declaration and write an executable projector script.

The kernel runs projector scripts as Unix pipeline processes:
- Receives all events as JSONL on stdin. Writes HTML on stdout. The kernel persists the output to KS_HOME/site/<projector_name>.html — do not write to disk yourself, just emit HTML on stdout.

The projector must build its state from the event stream by filtering for the consumed event names. It should render clean, valid HTML with inline CSS.

Write scripts in any language available on the system. Python 3 and bash are safe portable choices. Include the appropriate shebang. Use only standard libraries / builtins — no external dependencies.

Return ONLY a JSON object with this shape:
{"projector_script": "<full script source>"}

No prose, no markdown fences, just the JSON object.`

func buildCommandPrompt(cmd Command) string {
	return fmt.Sprintf(`Compile this command declaration into a command script.

COMMAND: %s
  description: %s
  params: %s

EVENT it produces:
  name: %s
  fields: %s

Write the command_script. It must produce an event with the declared name and populate its fields from argv params.`,
		cmd.Name,
		cmd.Description, jsonRepr(cmd.Params),
		cmd.Event.Name, jsonRepr(cmd.Event.Fields),
	)
}

func buildProjectorPrompt(p ProjectorDecl) string {
	return fmt.Sprintf(`Compile this projector declaration into a projector script.

PROJECTOR declaration:
  name: %s
  description: %s
  consumes: %s

Write the projector_script. It must filter events by the consumed names and render HTML.`,
		p.Name, p.Description, jsonRepr(p.Consumes),
	)
}

func parseCommandScript(content string) (string, error) {
	content = stripFences(content)
	var parsed struct {
		CommandScript string `json:"command_script"`
	}
	if err := json.Unmarshal([]byte(content), &parsed); err != nil {
		return "", fmt.Errorf("parse llm output: %w\nraw: %s", err, content)
	}
	if parsed.CommandScript == "" {
		return "", fmt.Errorf("llm returned empty command_script")
	}
	return parsed.CommandScript, nil
}

func parseProjectorScript(content string) (string, error) {
	content = stripFences(content)
	var parsed struct {
		ProjectorScript string `json:"projector_script"`
	}
	if err := json.Unmarshal([]byte(content), &parsed); err != nil {
		return "", fmt.Errorf("parse llm output: %w\nraw: %s", err, content)
	}
	if parsed.ProjectorScript == "" {
		return "", fmt.Errorf("llm returned empty projector_script")
	}
	return parsed.ProjectorScript, nil
}

func stripFences(content string) string {
	content = strings.TrimSpace(content)
	content = strings.TrimPrefix(content, "```json")
	content = strings.TrimPrefix(content, "```")
	content = strings.TrimSuffix(content, "```")
	return strings.TrimSpace(content)
}

func envOr(key, def string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return def
}

func jsonRepr(v any) string {
	b, _ := json.Marshal(v)
	return string(b)
}
